meta_product_name: "Health Connect"
meta_title: "Health Connect - Caring for yourself"
meta_description: "An easy way to help you for your care"
meta_image: "HealthConnect.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
